spring.application.name=Fight-Services
spring.config.import=optional:file:./.env.properties


spring.rabbitmq.host=${RABBITMQ_HOST:yak.lmq.cloudamqp.com}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:mkqpekbi}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:ZbiyBjraVzdd4oCfwxYeOlsBwhFB2NDx}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:mkqpekbi}

spring.data.redis.host=${REDIS_HOST:}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

voice.chat.base-url=${VOICE_CHAT_URL:https://lamentaciones-chat-voz-c8csfrfhgyb3d5hu.canadacentral-01.azurewebsites.net}
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://SantiagoS:sKAGAuaRQDenbh4@baseproyecto.h5zdq2x.mongodb.net/LobbyServices?retryWrites=true&w=majority}

app.base-url=http://localhost:8080
fight.partition.total-slots=${FIGHT_PARTITION_TOTAL_SLOTS:1}
fight.partition.current-slot=${FIGHT_PARTITION_CURRENT_SLOT:0}
fight.scheduler.pool-size=${FIGHT_SCHEDULER_POOL_SIZE:0}
fight.snapshot.fixed-delay-ms=${FIGHT_SNAPSHOT_FIXED_DELAY_MS:250}


stomp.relay.host=${RABBITMQ_HOST:yak.lmq.cloudamqp.com}
stomp.relay.port=${STOMP_PORT:61613}
stomp.relay.username=${RABBITMQ_USERNAME:mkqpekbi}
stomp.relay.password=${RABBITMQ_PASSWORD:ZbiyBjraVzdd4oCfwxYeOlsBwhFB2NDx}
stomp.relay.virtual-host=${RABBITMQ_VHOST:mkqpekbi}

management.endpoints.web.exposure.include=health
