# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - FightService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_819DA3F42ECF425489E07F9247A0D678 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_D3E3F913114C49308FB40E3C4A205EB6 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_819DA3F42ECF425489E07F9247A0D678 }}/fight-service:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_960F5AFBF39348E78D9543ABEECE8915 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FFAFB9845058474F993A89109900D43F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2898B7A143E44FF3ABCB676CAD9C7F13 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FightService'
          slot-name: 'Production'
          images: 'ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_819DA3F42ECF425489E07F9247A0D678 }}/fight-service:${{ github.sha }}'
          